name       : python-pyyaml-env-tag
version    : 0.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pyyaml_env_tag/pyyaml_env_tag-0.1.tar.gz : 70092675bda14fdec33b31ba77e7543de9ddc88f2e5b99160396572d11525bdb
license    : MIT
component  : programming.python
summary    : A custom YAML tag for referencing environment variables in YAML files.
description: |
    A custom YAML tag for referencing environment variables in YAML files.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
